CREATE TABLE WALLETS (
    WalletID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL UNIQUE,
    Balance DECIMAL(18, 2) NOT NULL DEFAULT 0 CHECK (Balance >= 0)
);

CREATE TABLE TRANSACTIONS (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY,
    WalletID INT NOT NULL,
    TransactionType VARCHAR(50) NOT NULL CHECK (TransactionType IN ('DEPOSIT', 'WITHDRAWAL', 'PAYMENT')),
    Amount DECIMAL(18, 2) NOT NULL CHECK (Amount > 0),
    TransactionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    CONSTRAINT FK_WalletTransaction FOREIGN KEY (WalletID) REFERENCES WALLETS(WalletID)
);